output_path: /ric_nas/Overhead_fisheye/COCO2017_YOLO
epochs: 50
batch: 16
mode: train
model_yaml: yolov8l-custom-obb.yaml  #runs/obb/habbof_obb100/weights/last.pt
device: '4'
imgsz: 608
save_period: 10
optimizer: SGD
lr: 0.001