output_path: /home/weiph/code/ultralytics/Overhead_fisheye/habbof_dataset  #LOAF_tiny4test  LOAF_YOLO_xyxy_from_rbox_not_none
epochs: 100
batch: 8
mode: train
model_yaml: yolov8l-obb.yaml  #runs/obb/habbof_obb292/weights/last.pt  yolov8l-obb.yaml
device: '6'
imgsz: 608
#rapid_train_strategy: True
save_period: 20
data_yaml: fine_tune_in_HC_M.yaml
#val_imgsz: 608

augment_dict:
  degrees: 90
  mosaic: 0
#  scale: 0.16
#  translate: 0

#optimizer_dict:
#  optimizer: 'SGD'
#  lr0: 0.0001
#  momentum: 0.9
#  weight_decay: 0.0001

#resume: True
#rapid_train_data: HCM