output_path: /ric_nas/Overhead_fisheye/LOAF_YOLO
epochs: 50
batch: 16
mode: train
model_yaml: yolov8l-cls-2-obb.yaml  #runs/obb/habbof_obb100/weights/last.pt
device: '7'
imgsz: 608
fine_tune_pretrain: True
optimizer: 'SGD'
lr: 0.0001