output_path: /home/weiph/code/ultralytics/Overhead_fisheye/COCO2017_YOLO
epochs: 100
batch: 8
mode: train
model_yaml: yolov8l-obb.yaml  #runs/obb/habbof_obb100/weights/last.pt
device: '2'
imgsz: 608
save_period: 20
data_yaml: COCO_tiny_one.yaml
augment_dict:
  degrees: 180
  mosaic: 0